name: Beepo
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.3+4

environment:
  sdk: ">=3.0.6 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  lottie: ^3.1.2
  get: ^4.6.5
  pin_code_fields: ^8.0.1
  flutter_screenutil: ^5.9.0
  fluttertoast: ^8.2.2
  hive: any
  hive_flutter: any
  iconsax: ^0.0.8
  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  web3dart: ^2.7.3
  flutter_dotenv: ^5.1.0
  bip39: ^1.0.6
  ed25519_hd_key: ^2.2.0
  hex: ^0.2.0
  provider: ^6.0.5
  http: ^1.1.0
  xmtp: ^1.3.1
  image_cropper: ^8.0.1
  image_picker: ^1.0.4
  intl: ^0.19.0
  encrypt: ^5.0.3
  aes_crypt_null_safe: ^3.0.0
  mongo_dart: ^0.10.3
  wallet: any
  flutter_hooks:
  ethereum_addresses: ^1.0.2
  decimal: ^2.3.3
  qr_flutter: ^4.1.0
  url_launcher:
  web3auth_flutter: ^5.0.4
  uni_links: ^0.5.1
  hawk_fab_menu: ^1.2.0
  shimmer: ^3.0.0
  grouped_list: ^6.0.0
  flutter_randomcolor: ^1.0.14
  retry: ^3.1.2
  shared_preferences: ^2.0.18
  quiver: ^3.2.1
  path: ^1.8.2
  path_provider: ^2.0.0
  drift: ^2.13.1
  flutter_app_badger: ^1.5.0
  blockies_ethereum: ^0.0.2
  sqlite3_flutter_libs: ^0.5.0
  string_to_color: ^2.0.0
  in_date_utils: ^1.2.0+2
  flutter_launcher_icons: ^0.14.1
  awesome_notifications: ^0.9.3+1
  flutter_dynamic_icon: ^2.1.0
  flutter_local_notifications: ^17.2.3
  async:
  camera: ^0.11.0+2
  image: ^4.1.3
  pull_to_refresh_notification: ^3.1.0
  local_auth: ^2.1.8
  webview_flutter: ^4.5.0
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.3.2
  hive_generator: any
  build_runner: any
  drift_dev: ^2.13.0

flutter_launcher_icons:
  image_path_android: "assets/icons/icon.png"
  image_path_ios: "assets/images/icon-1024x1024.png"
  android: true # can specify file name here e.g. "ic_launcher"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter_native_splash:
  background_image: "assets/splash.png"
  android: true
  ios: true

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/abi/
    - assets/icons/
    - assets/lottie/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 900
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 700
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Regular.ttf
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
    - family: SignikaNegative
      fonts:
        - asset: fonts/SignikaNegative-Bold.ttf
